#
# __  __     _             
#|  \/  |___| |_ __ _ _ __ 
#| |\/| / __| __/ _` | '__|
#| |  | \__ \ || (_| | |   
#|_|  |_|___/\__\__,_|_|   
#                       

#we can transfer variable into this makefile
DEBUG := true

OBJECT := $(strip $(wildcard *.hh))

ifdef DEBUG
$(warning OBJECT is $(OBJECT))
endif


.PHONY : ALL
ALL:
	 @echo "we now in ALL command"

.PHONY : clean
clean:
	@echo "We now in clean command"
